version: "3"
services:
    web:
        environment:
            VIRTUAL_HOST: twitteria.at,www.twitteria.at
            LETSENCRYPT_HOST: twitteria.at,www.twitteria.at
            LETSENCRYPT_EMAIL: contact@mariozechner.at
        networks:
            - reverse_proxy
networks:
    reverse_proxy:
        external:
            name: nginx-proxy
